version: 0.2

env:
  variables:
     SBT_VERSION: "1.1.2"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install bc
      - curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
      - dpkg -i sbt-$SBT_VERSION.deb
      - rm sbt-$SBT_VERSION.deb
      - apt-get update
      - apt-get install sbt
  pre_build:
    commands:
      - sbt test
  build:
    commands:
      - sbt compile
  post_build:
    commands:
      - sbt publish
